### ISSUE TITLE
ClassCastException at serialization when container type occours recursively in the type hierarchy

### ISSUE THREAD

**Issue by sandorfehervari** [vigoo/desert#332]
Maybe the title a bit misleading, but I can give a concrete example:
Given
```
  case class Media(url: String, size: Int)
  case class Slide(media: List[Media])
  case class TestClass(uri: String, slides: List[Slide])
```
When I try to derive a schema and a decoder and use it:
```
  object TestClass {
    implicit val testClassSchema: Schema[TestClass] = DeriveSchema.gen
    implicit val testClassCodec: BinaryCodec[TestClass] = DerivedBinaryCodec.derive
  }
    val serialized = serializeToArray[TestClass](
      TestClass(
        "test", 
        List(
          Slide(
            List(Media("media1", 500), Media("media2", 700))
          )
        )
      )
    )
```

It throws the following exception:

```
Exception in thread "main" java.lang.ClassCastException: class Messages$Media cannot be cast to class Messages$Slide (Messages$Media and Messages$Slide are in unnamed module of loader 'app')
	at io.github.vigoo.desert.zioschema.DerivedBinaryCodec$BinaryCodecDeriver.$anonfun$deriveRecord$5(DerivedBinaryCodec.scala:58)
	at scala.collection.immutable.List.map(List.scala:246)
	at io.github.vigoo.desert.zioschema.DerivedBinaryCodec$BinaryCodecDeriver.$anonfun$deriveRecord$4(DerivedBinaryCodec.scala:55)
	at io.github.vigoo.desert.internal.AdtCodec.serialize(AdtCodec.scala:67)
	at io.github.vigoo.desert.custom.BinarySerializerOps.write(BinarySerializerOps.scala:52)
	at io.github.vigoo.desert.custom.BinarySerializerOps.write$(BinarySerializerOps.scala:51)
	at io.github.vigoo.desert.custom.package$.write(package.scala:3)
	at io.github.vigoo.desert.Codecs$$anon$27.$anonfun$serializeWithKnownSize$1(Codecs.scala:504)
	at io.github.vigoo.desert.Codecs$$anon$27.$anonfun$serializeWithKnownSize$1$adapted(Codecs.scala:503)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
	at zio.Chunk$Arr.foreach(Chunk.scala:1685)
	at io.github.vigoo.desert.Codecs$$anon$27.serializeWithKnownSize(Codecs.scala:503)
	at io.github.vigoo.desert.Codecs$$anon$27.serialize(Codecs.scala:490)
	at io.github.vigoo.desert.Codecs$$anon$27.serialize(Codecs.scala:454)
	at io.github.vigoo.desert.BinarySerializer$$anon$1.serialize(BinaryCodec.scala:13)
	at io.github.vigoo.desert.BinaryCodec$$anon$5.serialize(BinaryCodec.scala:61)
	at io.github.vigoo.desert.internal.AdtCodec.serialize(AdtCodec.scala:302)
	at io.github.vigoo.desert.internal.AdtCodec.$anonfun$serialize$1(AdtCodec.scala:69)
	at io.github.vigoo.desert.internal.AdtCodec.$anonfun$serialize$1$adapted(AdtCodec.scala:68)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at io.github.vigoo.desert.internal.AdtCodec.serialize(AdtCodec.scala:68)
	at io.github.vigoo.desert.custom.BinarySerializerOps.write(BinarySerializerOps.scala:52)
	at io.github.vigoo.desert.custom.BinarySerializerOps.write$(BinarySerializerOps.scala:51)
	at io.github.vigoo.desert.custom.package$.write(package.scala:3)
	at io.github.vigoo.desert.Codecs$$anon$27.$anonfun$serializeWithKnownSize$1(Codecs.scala:504)
	at io.github.vigoo.desert.Codecs$$anon$27.$anonfun$serializeWithKnownSize$1$adapted(Codecs.scala:503)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
	at zio.Chunk$Arr.foreach(Chunk.scala:1685)
	at io.github.vigoo.desert.Codecs$$anon$27.serializeWithKnownSize(Codecs.scala:503)
	at io.github.vigoo.desert.Codecs$$anon$27.serialize(Codecs.scala:490)
	at io.github.vigoo.desert.Codecs$$anon$27.serialize(Codecs.scala:454)
	at io.github.vigoo.desert.BinarySerializer$$anon$1.serialize(BinaryCodec.scala:13)
	at io.github.vigoo.desert.BinaryCodec$$anon$5.serialize(BinaryCodec.scala:61)
	at io.github.vigoo.desert.internal.AdtCodec.serialize(AdtCodec.scala:302)
	at io.github.vigoo.desert.internal.AdtCodec.$anonfun$serialize$1(AdtCodec.scala:69)
	at io.github.vigoo.desert.internal.AdtCodec.$anonfun$serialize$1$adapted(AdtCodec.scala:68)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at io.github.vigoo.desert.internal.AdtCodec.serialize(AdtCodec.scala:68)
	at io.github.vigoo.desert.custom.BinarySerializerOps.write(BinarySerializerOps.scala:52)
	at io.github.vigoo.desert.custom.BinarySerializerOps.write$(BinarySerializerOps.scala:51)
	at io.github.vigoo.desert.custom.package$.write(package.scala:3)
	at io.github.vigoo.desert.BinarySerialization.serialize(BinarySerialization.scala:22)
	at io.github.vigoo.desert.BinarySerialization.serialize$(BinarySerialization.scala:14)
	at io.github.vigoo.desert.package$.serialize(package.scala:3)
	at io.github.vigoo.desert.BinarySerialization.serializeToStream(BinarySerialization.scala:74)
	at io.github.vigoo.desert.BinarySerialization.serializeToStream$(BinarySerialization.scala:68)
	at io.github.vigoo.desert.package$.serializeToStream(package.scala:3)
	at io.github.vigoo.desert.BinarySerialization.serializeToArray(BinarySerialization.scala:111)
	at io.github.vigoo.desert.BinarySerialization.serializeToArray$(BinarySerialization.scala:106)
	at io.github.vigoo.desert.package$.serializeToArray(package.scala:3)
	at Main$.main(Main.scala:24)
	at Main.main(Main.scala)
```

**Comment by sandorfehervari** [comment]
A gist which might help reproducing the issue: https://gist.github.com/sandorfehervari/4f3f459953af016af4c0947a05e6dedb
